
name: Flutter Build

on:
  push:
    branches: [main]

jobs:
  build_APK:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["apk --release", "linux --release", web]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Flutter Environment
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.3.10'
    - name: Get Packages
      run: flutter pub get
    - name: Run Tests
      run: | 
        echo Pass
        # flutter test
    - name: Build APK
      run: | 
        flutter build ${{ matrix.target }}
        flutter build apk
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Test Client
        path: build/app/outputs/apk/release/app-release.apk
        
  build_MacOS:
    name: Build ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["ios --no-codesign", macos] # ["apk --debug", "appbundle --debug", "ios --no-codesign", macos, web]
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          java-version: 11
          distribution: temurin
      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          channel: master
      - run: flutter config --enable-macos-desktop
      - run: flutter doctor -v

      # Checkout gallery code and get packages.
      - name: Checkout code
        uses: actions/checkout@v2 #8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - run: flutter pub get

      - run: flutter build ${{ matrix.target }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Test Client on MacOX
          path: build/app/outputs/ #apk/release/app-release.apk
