
name: Flutter Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Flutter Environment
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.3.10'
    - name: Get Packages
      run: flutter pub get
    - name: Run Tests
      run: | 
        echo Pass
        # flutter test
    - name: Build APK
      run: flutter build apk
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Test Client
        path: build/app/outputs/apk/release/app-release.apk
        
